# Alembic script template

"""Add timezone support to timestamps

Revision ID: 1a1f52d26e03
Revises: 4c8d2abc8f95
Create Date: 2025-11-06 01:51:55.668937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1f52d26e03'
down_revision: Union[str, None] = '4c8d2abc8f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
