"""Add constraints

Revision ID: 4c8d2abc8f95
Revises: fa961e7f0ed3
Create Date: 2025-11-04 15:28:48.725838

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c8d2abc8f95"
down_revision: str = "fa961e7f0ed3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson", schema=None) as batch_op:
        batch_op.create_index(
            "ix_lesson_skill_level_order_index", ["skill_level", "order_index"], unique=False
        )
        batch_op.create_unique_constraint(
            "uq_lesson_skill_level_order_index", ["skill_level", "order_index"]
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index("ix_user_created_at", ["created_at"], unique=False)
        batch_op.create_check_constraint(
            "check_assessment_score_range",
            "assessment_score IS NULL OR (assessment_score >= 0 AND assessment_score <= 100)",
        )

    with op.batch_alter_table("user_progress", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_progress_user_id_status", ["user_id", "status"], unique=False
        )
        batch_op.create_unique_constraint("uq_user_progress_user_lesson", ["user_id", "lesson_id"])
        batch_op.create_check_constraint(
            "check_last_score_range",
            "last_score IS NULL OR (last_score >= 0 AND last_score <= 100)",
        )

    with op.batch_alter_table("user_session", schema=None) as batch_op:
        batch_op.create_index("ix_user_session_updated_at", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_session", schema=None) as batch_op:
        batch_op.drop_index("ix_user_session_updated_at")

    with op.batch_alter_table("user_progress", schema=None) as batch_op:
        batch_op.drop_constraint("check_last_score_range", type_="check")
        batch_op.drop_constraint("uq_user_progress_user_lesson", type_="unique")
        batch_op.drop_index("ix_user_progress_user_id_status")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("check_assessment_score_range", type_="check")
        batch_op.drop_index("ix_user_created_at")

    with op.batch_alter_table("lesson", schema=None) as batch_op:
        batch_op.drop_constraint("uq_lesson_skill_level_order_index", type_="unique")
        batch_op.drop_index("ix_lesson_skill_level_order_index")
    # ### end Alembic commands ###
