# Alembic script template

"""Initial schema

Revision ID: fa961e7f0ed3
Revises: 
Create Date: 2025-11-01 01:10:21.838755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa961e7f0ed3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('skill_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='skilllevel'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('theory_content', sa.JSON(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('exercises', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_lesson_skill_level'), 'lesson', ['skill_level'], unique=False)
    op.create_table('user',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('skill_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='skilllevel'), nullable=False),
    sa.Column('learning_goal', sa.Enum('ACADEMIC', 'PROFESSIONAL', 'CREATIVE', name='learninggoal'), nullable=False),
    sa.Column('current_lesson_id', sa.Integer(), nullable=True),
    sa.Column('assessment_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='lessonstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_score', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_lesson_id'), 'user_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('user_session',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('ONBOARDING', 'LEARNING', 'PRACTICING', 'MENU', name='sessionstate'), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_session')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_lesson_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_lesson_skill_level'), table_name='lesson')
    op.drop_table('lesson')
    # ### end Alembic commands ###
